create table if not exists public.games (
  room_code text primary key,
  state_json jsonb not null,
  source_client text,
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create table if not exists public.participants (
  room_code text not null,
  client_id text not null,
  role text not null check (role in ('host', 'participant')),
  last_seen_at timestamptz not null default timezone('utc'::text, now()),
  primary key (room_code, client_id)
);

create table if not exists public.game_actions (
  id bigint generated by default as identity primary key,
  room_code text not null,
  client_id text not null,
  action_type text not null,
  payload jsonb,
  created_at timestamptz not null default timezone('utc'::text, now())
);

alter table public.games enable row level security;
alter table public.participants enable row level security;
alter table public.game_actions enable row level security;

-- Required for postgres_changes filtered subscriptions to work correctly
alter table public.games replica identity full;
alter table public.participants replica identity full;
alter table public.game_actions replica identity full;

-- Constrain room code shape so anonymous writers cannot create arbitrary rows.
alter table public.games
  drop constraint if exists games_room_code_format;
alter table public.games
  add constraint games_room_code_format
  check (room_code ~ '^[A-Z0-9-]{3,16}$');

drop policy if exists "allow anon read games" on public.games;
create policy "allow anon read games"
  on public.games
  for select
  to anon
  using (true);

drop policy if exists "allow anon upsert games" on public.games;
create policy "allow anon insert games"
  on public.games
  for insert
  to anon
  with check (true);

create policy "allow anon update games"
  on public.games
  for update
  to anon
  using (true)
  with check (true);

drop policy if exists "allow anon read participants" on public.participants;
create policy "allow anon read participants"
  on public.participants
  for select
  to anon
  using (true);

drop policy if exists "allow anon write participants" on public.participants;
create policy "allow anon insert participants"
  on public.participants
  for insert
  to anon
  with check (true);

create policy "allow anon update participants"
  on public.participants
  for update
  to anon
  using (true)
  with check (true);

drop policy if exists "allow anon read actions" on public.game_actions;
create policy "allow anon read actions"
  on public.game_actions
  for select
  to anon
  using (true);

drop policy if exists "allow anon write actions" on public.game_actions;
create policy "allow anon insert actions"
  on public.game_actions
  for insert
  to anon
  with check (true);
