create table if not exists public.games (
  room_code text primary key,
  state_json jsonb not null,
  source_client text,
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create table if not exists public.participants (
  room_code text not null,
  client_id text not null,
  role text not null check (role in ('host', 'participant')),
  last_seen_at timestamptz not null default timezone('utc'::text, now()),
  primary key (room_code, client_id)
);

create table if not exists public.game_actions (
  id bigint generated by default as identity primary key,
  room_code text not null,
  client_id text not null,
  action_type text not null,
  payload jsonb,
  created_at timestamptz not null default timezone('utc'::text, now())
);

alter table public.games enable row level security;
alter table public.participants enable row level security;
alter table public.game_actions enable row level security;

drop policy if exists "allow anon read games" on public.games;
create policy "allow anon read games"
  on public.games
  for select
  to anon
  using (true);

drop policy if exists "allow anon upsert games" on public.games;
create policy "allow anon upsert games"
  on public.games
  for all
  to anon
  using (true)
  with check (true);

drop policy if exists "allow anon read participants" on public.participants;
create policy "allow anon read participants"
  on public.participants
  for select
  to anon
  using (true);

drop policy if exists "allow anon write participants" on public.participants;
create policy "allow anon write participants"
  on public.participants
  for all
  to anon
  using (true)
  with check (true);

drop policy if exists "allow anon read actions" on public.game_actions;
create policy "allow anon read actions"
  on public.game_actions
  for select
  to anon
  using (true);

drop policy if exists "allow anon write actions" on public.game_actions;
create policy "allow anon write actions"
  on public.game_actions
  for all
  to anon
  using (true)
  with check (true);
